language: java
script: mvn clean verify -f bundles/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8
deploy:
  provider: releases
  file_glob: true
  file: bundle/fr.univnantes.alma.repository/target/products/ALMAServer-*.zip
  on:
    repo: PMAlma2015RSKABDSAA/ManagementProject
    tags: true
    all_branches: false
